### ISSUE TITLE
Q: IS this compatible with UmbracoCloud-V7 sites?

### ISSUE THREAD

**Issue by c9mb** [prjseal/CodeShare.TLS1.2.Umbraco#2]
I need to get TLS-1.2 working on my Cloud-V7 sites to meet Azure phasing out of TLS-1.0/1.1

Would this be a valid option?

**Comment by prjseal** [comment]
Hi Mike.
Yes I believe so. If you put it in your bin folder it should enable tls1.2

**Comment by prjseal** [comment]
Hi Mike
Yes I believe so. If you put it in your bin folder it should enable TLS 1.2

Kind regards

Paul

**Comment by c9mb** [comment]
Many thanks for that - I used your code in my own ApplicationStarted event handler, and it seems to work and makes the health-check dashboard happy.
Of course, that doesn't make various our.packages actually request using TLS-1.2 - but now at least they can, if they are updated to be compliant.
